### ISSUE TITLE
Add common.py 

### ISSUE THREAD

**Issue by gahooa** [appcove/developer-software#6]
Build scripts share a lot of common code.  Move it into `common.py` and import it with `from common import *`

**Comment by DilecPadovani** [comment]
Done in 4f122ac636bc84276c128a9b9f54e7c438f98b85

**Comment by DilecPadovani** [comment]
@gahooa as of now I would leave it as it is. Maybe in the future, we can have for each program something like this:
### git-excess.yaml
``` yaml
project_name: "git-excess"
type: "rust"
binaries: " path1, path2 "
```
The python script will be responsible for building the `.deb` according to the info provided in the YAML
